# Repository configuration
repository: "https://github.com/astrolabsoftware/fink-broker.git"
repo_name: "fink-broker"

# Optional: override default directories (will use /tmp fallbacks for development)
# cache_dir: "/var/cache/home-ci"
# state_dir: "/var/lib/home-ci/state"
# workspace_dir: "/var/lib/home-ci/workspaces"
# log_dir: "/var/log/home-ci"
cache_dir: "/tmp/home-ci/cache"
state_dir: "/tmp/home-ci/state"
workspace_dir: "/tmp/home-ci/workspaces"
log_dir: "/tmp/home-ci/log"

# Test configuration
check_interval: 30s
test_script: "e2e/run.sh"
options: "-c"
recent_commits_within: 240h
test_timeout: 60m
fetch_remote: true
max_concurrent_runs: 1
keep_time: 2h

# TODO
cleanup:
  after_e2e: false 
  script: "e2e/clean.sh"

github_actions_dispatch:
  enabled: true
  github_repo: "astrolabsoftware/fink-broker"
  github_token_file: "/home/fink-ci/secret.yaml"
  dispatch_type: "test-home-ci-no-token"

